### ISSUE TITLE
Some questions on the calculations

### ISSUE THREAD

**Issue by oliexdev** [prototux/MIBCS-reverse-engineering#1]
First of all, great reverse engineering work :1st_place_medal:  I integrated your implementation into openScale but I have some questions.

https://github.com/prototux/MIBCS-reverse-engineering/blob/15e6bd6654e69834b97f965de78b9b5d2bddcfa2/body.py#L171

I think it should be male?

https://github.com/prototux/MIBCS-reverse-engineering/blob/15e6bd6654e69834b97f965de78b9b5d2bddcfa2/body.py#L194

I think a = is missing!?

https://github.com/prototux/MIBCS-reverse-engineering/blob/15e6bd6654e69834b97f965de78b9b5d2bddcfa2/body.py#L191

What is d6?

I guess I am not really understand the *scale methods? Are these the range limits to evaluate the results?

**Comment by prototux** [comment]
Thanks, i've fixed the bugs (shouldn't do refactoring at 4AM). d6 was "self.weight" in the [first pass of implementation](https://github.com/prototux/MIBCS-reverse-engineering/blob/3a490064a9910407b9cd6c082710a7d32cae9343/calculations.py#L462)

The scales are exactly this, they're the boundaries for the little "scale" that's in mi fit (or other apps), for example ![here](https://ksassets.timeincuk.net/wp/uploads/sites/54/2018/12/IMG_1803-1024x910.jpg) with the visceral fat, in this case `getVisceralFatScale()` would return `[10, 15]` (this is currently the case as the values are hardcoded for everybody in the original library).

They're completly optional for the calculations, that's why i've put them in some other functions than the "main" ones that does the calculations.

**Comment by oliexdev** [comment]
Ok I understand. Btw on the openScale wiki I wrote some documentation about the [mi scale v1](https://github.com/oliexdev/openScale/wiki/Xiaomi-Bluetooth-Mi-Scale) which behave exactly like the v2 but without the body measurements calculations.

The advertisment Bluetooth packets are send if you are standing on the scale but since the scale saves your measurement on the scale itself (and never deleted) you can ignore them.
You can fetch the saved measurements on the scale if you do these steps:

> To get only the recently saved history weight data, send following command process to custom > characteristic (0x2a2f):
>
>  Set notification on for weight measurement history
>  Write value 0x01 0xFF 0xFF 0xFF 0xFF on characteristic (You will receive 0x01 0x?? 0xFF 0xFF 0xFF 0xFF via notification. ?? is the amount of new history data)
>  Set notification off for weight measurement history
>  Set notification on for weight measurement history
>  Write value 0x02 to invoke receiving the recently saved history data

**Comment by prototux** [comment]
Thanks, i've also started to play with these (for `BLE_protocol.md`) last night, but i don't get any notification in my sandbox as for now, i don't know if it's a bug in my code or bluepy yet.

**Comment by prototux** [comment]
The calculations for females are quite wrong, going to debug and fix that (see #2 )

**Comment by oliexdev** [comment]
thanks I fixed the calculation too in openScale

Did you turn on the notification flag on characteristic `00002a2f-0000-3512-2118-0009af100700`?
At least I can't see it in your `app.py` source code....

**Comment by oliexdev** [comment]
For testing, you can do it easily manually with the [BLE Scanner App](https://play.google.com/store/apps/details?id=com.macdom.ble.blescanner) and send the `0x02` byte to `00002a2f-0000-3512-2118-0009af100700` to invoke receiving the history data.
